vim.cmd 'highlight clear'
if vim.fn.exists 'syntax_on' == 1 then vim.cmd 'syntax reset' end

vim.o.termguicolors = true
vim.g.colors_name = 'cool-panda'

local colors = {
  bg = '#212121',
  bg_dark = '#1a1a1a',
  bg_deep = '#101010',
  bg_highlight = '#171717',
  bg_subtle = '#2f2f2f',
  bg_visual = '#18434d',
  bg_word = '#585568',
  bg_word_strong = '#796063',
  fg = '#d8dee9',
  fg_bright = '#eeffff',
  fg_muted = '#616161',
  line_nr = '#424242',
  comment = '#4f5051',
  teal = '#5ae4ca',
  cyan = '#2bd6ec',
  blue = '#76c3ff',
  blue_builtin = '#66aef7',
  lavender = '#9daeff',
  lavender_light = '#a8b5ff',
  purple = '#a890ca',
  pink = '#e6789e',
  tag = '#c29fdd',
  property = '#8ddfd7',
  variable = '#daeeed',
  parameter = '#b4fae8',
  red = '#bf616a',
  green = '#a3be8c',
  diff_add = '#396965',
  diff_delete = '#71545e',
}

local highlights = {
  Normal = { fg = colors.fg, bg = colors.bg },
  NormalNC = { fg = colors.fg, bg = colors.bg },
  NormalFloat = { fg = colors.fg_bright, bg = colors.bg },
  FloatBorder = { fg = colors.comment, bg = colors.bg },
  FloatTitle = { fg = colors.teal, bg = colors.bg, bold = true },
  ColorColumn = { bg = colors.bg_subtle },
  Conceal = { fg = colors.fg_muted },
  Cursor = { fg = colors.bg, bg = colors.pink },
  CursorIM = { link = 'Cursor' },
  TermCursor = { link = 'Cursor' },
  CursorColumn = { bg = colors.bg_highlight },
  CursorLine = { bg = colors.bg_highlight },
  CursorLineNr = { fg = colors.fg, bg = colors.bg_highlight, bold = true },
  LineNr = { fg = colors.line_nr },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  SignColumn = { fg = colors.fg_muted, bg = colors.bg },
  FoldColumn = { fg = colors.fg_muted, bg = colors.bg },
  Folded = { fg = colors.comment, bg = colors.bg_dark },
  NonText = { fg = colors.line_nr },
  SpecialKey = { fg = colors.line_nr },
  Whitespace = { fg = colors.bg_subtle },
  EndOfBuffer = { fg = colors.bg },
  WinSeparator = { fg = colors.bg_deep, bg = colors.bg },
  VertSplit = { link = 'WinSeparator' },
  StatusLine = { fg = colors.fg_bright, bg = colors.bg_highlight },
  StatusLineNC = { fg = colors.fg_muted, bg = colors.bg_highlight },
  TabLine = { fg = colors.fg_muted, bg = colors.bg },
  TabLineFill = { bg = colors.bg },
  TabLineSel = { fg = colors.teal, bg = colors.bg, bold = true },
  WinBar = { fg = colors.fg_bright, bg = colors.bg },
  WinBarNC = { fg = colors.fg_muted, bg = colors.bg },
  MsgArea = { fg = colors.fg_bright, bg = colors.bg },
  ModeMsg = { fg = colors.teal, bold = true },
  MoreMsg = { fg = colors.green },
  Question = { fg = colors.teal },
  ErrorMsg = { fg = colors.pink, bold = true },
  WarningMsg = { fg = colors.green },
  Title = { fg = colors.property, bold = true },
  Directory = { fg = colors.blue },
  Visual = { bg = colors.bg_visual },
  VisualNOS = { bg = colors.bg_visual },
  Search = { fg = colors.fg_bright, bg = colors.bg_visual },
  CurSearch = { fg = colors.bg, bg = colors.teal, bold = true },
  IncSearch = { fg = colors.bg, bg = colors.purple },
  Substitute = { fg = colors.bg, bg = colors.pink },
  MatchParen = { fg = colors.bg, bg = colors.tag, bold = true },
  QuickFixLine = { bg = colors.bg_visual, bold = true },
  Pmenu = { fg = colors.fg_bright, bg = colors.bg },
  PmenuSel = { fg = colors.teal, bg = colors.bg_highlight },
  PmenuSbar = { bg = colors.bg_subtle },
  PmenuThumb = { bg = colors.property },
  PmenuMatch = { fg = colors.property, bold = true },
  PmenuMatchSel = { fg = colors.teal, bg = colors.bg_highlight, bold = true },
  PmenuKind = { fg = colors.lavender },
  PmenuKindSel = { fg = colors.lavender, bg = colors.bg_highlight },
  WildMenu = { fg = colors.teal, bg = colors.bg_highlight },

  Comment = { fg = colors.comment, italic = true },
  Constant = { fg = colors.lavender },
  String = { fg = colors.teal },
  Character = { link = 'String' },
  Number = { link = 'Constant' },
  Boolean = { link = 'Constant' },
  Float = { link = 'Constant' },
  Identifier = { fg = colors.variable },
  Variable = { fg = colors.variable },
  Parameter = { fg = colors.parameter },
  Property = { fg = colors.property },
  Function = { fg = colors.blue },
  FunctionBuiltin = { fg = colors.blue_builtin },
  Statement = { fg = colors.purple },
  Conditional = { link = 'Statement' },
  Repeat = { link = 'Statement' },
  Label = { link = 'Statement' },
  Keyword = { link = 'Statement' },
  Exception = { link = 'Statement' },
  Operator = { fg = colors.cyan },
  PreProc = { fg = colors.lavender },
  Include = { fg = colors.purple },
  Define = { link = 'PreProc' },
  Macro = { link = 'PreProc' },
  PreCondit = { link = 'PreProc' },
  Type = { fg = colors.lavender },
  TypeBuiltin = { fg = colors.lavender_light },
  StorageClass = { link = 'Type' },
  Structure = { link = 'Type' },
  Typedef = { link = 'Type' },
  Special = { fg = colors.cyan },
  SpecialChar = { link = 'Special' },
  Tag = { fg = colors.tag },
  Delimiter = { fg = colors.fg },
  SpecialComment = { fg = colors.lavender },
  Debug = { fg = colors.purple },
  Underlined = { fg = colors.blue, underline = true },
  Ignore = { fg = colors.comment },
  Error = { fg = colors.pink, bold = true },
  Todo = { fg = colors.bg, bg = colors.green, bold = true },

  DiffAdd = { bg = colors.diff_add },
  DiffChange = { bg = colors.bg_word },
  DiffDelete = { bg = colors.diff_delete },
  DiffText = { bg = colors.bg_word_strong, bold = true },
  Added = { fg = colors.teal },
  Changed = { fg = colors.purple },
  Removed = { fg = colors.pink },
  SpellBad = { sp = colors.red, undercurl = true },
  SpellCap = { sp = colors.blue, undercurl = true },
  SpellLocal = { sp = colors.cyan, undercurl = true },
  SpellRare = { sp = colors.purple, undercurl = true },

  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.green },
  DiagnosticInfo = { fg = colors.blue },
  DiagnosticHint = { fg = colors.property },
  DiagnosticOk = { fg = colors.teal },
  DiagnosticUnderlineError = { sp = colors.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = colors.green, undercurl = true },
  DiagnosticUnderlineInfo = { sp = colors.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = colors.property, undercurl = true },
  DiagnosticVirtualTextError = { fg = colors.red, bg = colors.bg_highlight },
  DiagnosticVirtualTextWarn = { fg = colors.green, bg = colors.bg_highlight },
  DiagnosticVirtualTextInfo = { fg = colors.blue, bg = colors.bg_highlight },
  DiagnosticVirtualTextHint = { fg = colors.property, bg = colors.bg_highlight },
  DiagnosticUnnecessary = { fg = colors.comment },
  LspReferenceText = { bg = colors.bg_word },
  LspReferenceRead = { bg = colors.bg_word },
  LspReferenceWrite = { bg = colors.bg_word_strong },
  LspInlayHint = { fg = colors.fg_muted, bg = colors.bg_highlight, italic = true },
  LspCodeLens = { fg = colors.fg_muted },
  LspCodeLensSeparator = { fg = colors.line_nr },

  ['@comment'] = { link = 'Comment' },
  ['@comment.documentation'] = { fg = colors.comment },
  ['@comment.error'] = { fg = colors.pink, bold = true },
  ['@comment.warning'] = { fg = colors.green, bold = true },
  ['@comment.todo'] = { link = 'Todo' },
  ['@constant'] = { link = 'Constant' },
  ['@constant.builtin'] = { link = 'Constant' },
  ['@constant.macro'] = { link = 'Constant' },
  ['@string'] = { link = 'String' },
  ['@string.documentation'] = { link = 'String' },
  ['@string.escape'] = { fg = colors.cyan },
  ['@string.regexp'] = { fg = colors.teal },
  ['@character'] = { link = 'Character' },
  ['@number'] = { link = 'Number' },
  ['@boolean'] = { link = 'Boolean' },
  ['@variable'] = { link = 'Variable' },
  ['@variable.builtin'] = { fg = colors.purple },
  ['@variable.parameter'] = { link = 'Parameter' },
  ['@variable.member'] = { link = 'Property' },
  ['@property'] = { link = 'Property' },
  ['@module'] = { link = 'Type' },
  ['@module.builtin'] = { link = 'TypeBuiltin' },
  ['@label'] = { link = 'Statement' },
  ['@function'] = { link = 'Function' },
  ['@function.builtin'] = { link = 'FunctionBuiltin' },
  ['@function.call'] = { link = 'Function' },
  ['@function.macro'] = { link = 'PreProc' },
  ['@function.method'] = { link = 'Function' },
  ['@function.method.call'] = { link = 'Function' },
  ['@constructor'] = { link = 'Type' },
  ['@operator'] = { link = 'Operator' },
  ['@keyword'] = { link = 'Keyword' },
  ['@keyword.coroutine'] = { link = 'Keyword' },
  ['@keyword.function'] = { link = 'Keyword' },
  ['@keyword.operator'] = { link = 'Operator' },
  ['@keyword.import'] = { fg = colors.purple },
  ['@keyword.type'] = { link = 'Keyword' },
  ['@keyword.modifier'] = { link = 'Type' },
  ['@type'] = { link = 'Type' },
  ['@type.builtin'] = { link = 'TypeBuiltin' },
  ['@type.definition'] = { link = 'Type' },
  ['@attribute'] = { fg = '#8fa9ff' },
  ['@punctuation.delimiter'] = { link = 'Delimiter' },
  ['@punctuation.bracket'] = { link = 'Delimiter' },
  ['@punctuation.special'] = { link = 'Operator' },
  ['@tag'] = { link = 'Tag' },
  ['@tag.attribute'] = { link = 'Property' },
  ['@tag.delimiter'] = { link = 'Operator' },
  ['@markup.heading'] = { fg = colors.property, bold = true },
  ['@markup.heading.marker'] = { fg = colors.teal, bold = true },
  ['@markup.strong'] = { fg = colors.lavender, bold = true },
  ['@markup.italic'] = { fg = colors.purple, italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.quote'] = { fg = colors.lavender },
  ['@markup.math'] = { fg = colors.cyan },
  ['@markup.link'] = { fg = colors.blue, italic = true },
  ['@markup.link.label'] = { fg = colors.property },
  ['@markup.link.url'] = { fg = colors.property, underline = true },
  ['@markup.raw'] = { fg = colors.teal, italic = true },
  ['@markup.list'] = { fg = colors.purple },
  ['@diff.plus'] = { link = 'Added' },
  ['@diff.delta'] = { link = 'Changed' },
  ['@diff.minus'] = { link = 'Removed' },

  ['@lsp.type.class'] = { link = 'Type' },
  ['@lsp.type.decorator'] = { link = '@attribute' },
  ['@lsp.type.enum'] = { link = 'Type' },
  ['@lsp.type.enumMember'] = { link = 'Constant' },
  ['@lsp.type.function'] = { link = 'Function' },
  ['@lsp.type.interface'] = { link = 'Type' },
  ['@lsp.type.macro'] = { link = 'PreProc' },
  ['@lsp.type.method'] = { link = 'Function' },
  ['@lsp.type.namespace'] = { link = 'Type' },
  ['@lsp.type.number'] = { link = 'Number' },
  ['@lsp.type.operator'] = { link = 'Operator' },
  ['@lsp.type.parameter'] = { link = 'Parameter' },
  ['@lsp.type.property'] = { link = 'Property' },
  ['@lsp.type.string'] = { link = 'String' },
  ['@lsp.type.struct'] = { link = 'Type' },
  ['@lsp.type.type'] = { link = 'Type' },
  ['@lsp.type.typeParameter'] = { link = 'Type' },
  ['@lsp.type.variable'] = { link = 'Variable' },

  GitSignsAdd = { fg = colors.teal },
  GitSignsChange = { fg = colors.property },
  GitSignsDelete = { fg = colors.pink },
  TelescopeNormal = { fg = colors.fg_bright, bg = colors.bg },
  TelescopeBorder = { fg = colors.comment, bg = colors.bg },
  TelescopePromptNormal = { fg = colors.fg_bright, bg = colors.bg_dark },
  TelescopePromptBorder = { fg = colors.property, bg = colors.bg_dark },
  TelescopePromptTitle = { fg = colors.bg, bg = colors.property, bold = true },
  TelescopePreviewTitle = { fg = colors.bg, bg = colors.blue, bold = true },
  TelescopeResultsTitle = { fg = colors.bg, bg = colors.purple, bold = true },
  TelescopeSelection = { fg = colors.teal, bg = colors.bg_highlight },
  TelescopeMatching = { fg = colors.property, bold = true },
  WhichKey = { fg = colors.cyan },
  WhichKeyGroup = { fg = colors.property },
  WhichKeyDesc = { fg = colors.fg },
  WhichKeyNormal = { fg = colors.fg, bg = colors.bg },
  NeoTreeNormal = { fg = colors.fg, bg = colors.bg_dark },
  NeoTreeNormalNC = { fg = colors.fg, bg = colors.bg_dark },
  NeoTreeDirectoryName = { fg = colors.blue },
  NeoTreeDirectoryIcon = { fg = colors.property },
  NeoTreeRootName = { fg = colors.teal, bold = true },
  NeoTreeFileNameOpened = { fg = colors.teal },
  NeoTreeGitAdded = { fg = colors.teal },
  NeoTreeGitModified = { fg = colors.property },
  NeoTreeGitDeleted = { fg = colors.pink },
  NeoTreeIndentMarker = { fg = colors.line_nr },
  BlinkCmpMenu = { link = 'Pmenu' },
  BlinkCmpMenuSelection = { link = 'PmenuSel' },
  BlinkCmpLabelMatch = { fg = colors.property, bold = true },
  BlinkCmpKind = { fg = colors.lavender },
  BlinkCmpDoc = { link = 'NormalFloat' },
  BlinkCmpDocBorder = { link = 'FloatBorder' },
  MiniStatuslineModeNormal = { fg = colors.bg, bg = colors.teal, bold = true },
  MiniStatuslineModeInsert = { fg = colors.bg, bg = colors.blue, bold = true },
  MiniStatuslineModeVisual = { fg = colors.bg, bg = colors.purple, bold = true },
  MiniStatuslineModeReplace = { fg = colors.bg, bg = colors.pink, bold = true },
  MiniStatuslineModeCommand = { fg = colors.bg, bg = colors.lavender, bold = true },
  MiniStatuslineDevinfo = { fg = colors.fg, bg = colors.bg_subtle },
  MiniStatuslineFilename = { fg = colors.fg, bg = colors.bg_highlight },
  MiniStatuslineFileinfo = { fg = colors.fg, bg = colors.bg_subtle },
  MiniStatuslineInactive = { fg = colors.fg_muted, bg = colors.bg_highlight },
  TodoBgFIX = { fg = colors.bg, bg = colors.pink, bold = true },
  TodoBgWARN = { fg = colors.bg, bg = colors.green, bold = true },
  TodoBgTODO = { fg = colors.bg, bg = colors.blue, bold = true },
  TodoBgNOTE = { fg = colors.bg, bg = colors.property, bold = true },
  IblIndent = { fg = colors.bg_subtle },
  IblScope = { fg = colors.property },
}

for group, settings in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, settings)
end

vim.g.terminal_color_0 = '#2a2a2a'
vim.g.terminal_color_1 = colors.pink
vim.g.terminal_color_2 = '#4dd9bf'
vim.g.terminal_color_3 = '#4dd9bf'
vim.g.terminal_color_4 = '#92a3ff'
vim.g.terminal_color_5 = '#b794d1'
vim.g.terminal_color_6 = '#4db8c4'
vim.g.terminal_color_7 = colors.fg
vim.g.terminal_color_8 = colors.comment
vim.g.terminal_color_9 = colors.pink
vim.g.terminal_color_10 = '#4dd9bf'
vim.g.terminal_color_11 = '#4dd9bf'
vim.g.terminal_color_12 = '#92a3ff'
vim.g.terminal_color_13 = '#b794d1'
vim.g.terminal_color_14 = '#4db8c4'
vim.g.terminal_color_15 = '#ffffff'
